---
title: "zihangxu"
format:
  html:
    theme: default
---

```{r}
library(fpp)
library(forecast)
library(backtest)
library(quantmod)
library(tseries)
library(zoo)
library(lubridate)
library(tseries)
library(TSA)
library(scales)
library(MTS)
library(readxl)
```
#the data we prepare
```{r}
anc1p <- mat %>%
  filter(subpop=="anc1p") %>%
  select(mnthyr, rate, subpop) 


anc1p_pred <- anc1p %>%
  slice(-(52:54))
anc1p_ts <- ts(anc1p_pred$rate)
anc1ptrue_ts=ts(anc1p$rate)
```
#plot, acf and pacf
```{r}
adf.test(anc1p_ts)
par(mfrow=c(1,3))
plot(anc1p_ts,ylab="rate")
acf(anc1p_ts)
pacf(anc1p_ts)
#seems like the data is non-stationary
#try diff to buil ARIMA, basically we can try log transformation when we have increase trend data
d1=diff(anc1p_ts,differences=1)
par(mfrow=c(1,3))
plot(d1,ylab="rate")
acf(d1)
pacf(d1)
adf.test(d1)
eacf(d1,ma.max = 10)

d2=diff(anc1p_ts,differences=2)
par(mfrow=c(1,3))
plot(d2,ylab="rate")
acf(d2)
pacf(d2)
adf.test(d2)
eacf(d2,ma.max = 10)
#much better
#consider diff=1
# consider ar3,4,15 from pacf
# ma3,4 from acf
```
#try auto first arima(2,1,3)
```{r}

anc1p_arim <- auto.arima(d1)
anc1p_arim
```
#arima(2,1,3)
```{r}
arima213=Arima(anc1p_ts, order=c(2,1,3))
tsdiag(arima213)
checkresiduals(arima213)


autoplot(forecast(arima213,h=3))
plot(anc1ptrue_ts)
backtest(arima213,anc1ptrue_ts,orig=52)

anc1p_forecast <- data.frame(forecast(arima213, h=3)) %>%
  mutate(mnthyr=ymd(c("2022-04-01","2022-05-01","2022-06-01")),
         forecast=1) %>%
  select(mnthyr,
         rate=1,
         lower=4,
         upper=5,
         forecast)
#here the forecast is the diff like Yt-Y(t-1)

ggplot(anc1p, aes(mnthyr, rate)) +
  geom_point(color="dodgerblue") +
  stat_smooth() +
  geom_point(data=anc1p_forecast, aes(y=rate), color="darkgoldenrod2") +
  stat_smooth(data=anc1p_forecast, aes(y=rate), color="darkgoldenrod2",fill="darkgoldenrod2") +
  geom_ribbon(data=anc1p_forecast, aes(ymin=lower, ymax=upper),
              fill="darkgoldenrod2",
              alpha=.2) +
  scale_y_continuous(limits=c(0,.5),
                     labels=percent_format(accuracy=1))

#try to forecast 6 step
out.arim=Arima(anc1ptrue_ts,order=c(2,1,3))
tsdiag(out.arim)
checkresiduals(out.arim)

out.arim.pred <- data.frame(forecast(out.arim, h=6)) %>%
  mutate(mnthyr=ymd(c("2022-07-01","2022-08-01","2022-09-01", "2022-10-01","2022-11-01","2022-12-01")),
         forecast=1) %>%
  select(mnthyr, 
         rate=1,
         lower=4,
         upper=5,
         forecast)
out.arim.dat <- anc1p %>%
  select(-3) %>%
  mutate(lower=NA,
         upper=NA,
         forecast=0) %>%
  bind_rows(out.arim.pred)
ggplot(out.arim.dat, aes(mnthyr, rate)) + 
  geom_point(data=out.arim.dat[1:54,], 
             color="dodgerblue2",
             size=1,
             alpha=.8) + 
  stat_smooth(#data=filter(out.arim.dat, forecast==0),
              data=out.arim.dat[1:55,],
              color="dodgerblue2") +
  scale_x_date(labels=date_format("%b-%y"),
               breaks=date_breaks("4 months")) +
  geom_point(data=filter(out.arim.dat, forecast==1),
             color="darkgoldenrod2",
             size=1,
             alpha=.8) +
  stat_smooth(data=filter(out.arim.dat, forecast==1),
              color="darkgoldenrod2",
              method="lm",
              se=F,
              fill="darkgoldenrod2",
              alpha=.2,
              size=.8) +
  # stat_smooth(data=filter(out.arim.dat, forecast==1),
  #             aes(y=lower),
  #             color="darkgoldenrod2",
  #             linetype="dotdash",
  #             size=1.2) + 
  # stat_smooth(data=filter(out.arim.dat, forecast==1),
  #             aes(y=upper),
  #             color="darkgoldenrod2",
  #             linetype="dotdash",
  #             size=1.2) + 
  geom_ribbon(aes(ymin=lower, ymax=upper),
              fill="darkgoldenrod2",
              alpha=.2) +
  scale_y_continuous(limits=c(0,.5),
                     labels=percent_format(accuracy=1)) +
  labs(x="",
       y="",
       title="ANC Coverage 1st Trimester with six-month forecast")
backtest(out.arim,anc1ptrue_ts,orig=48)


```

#try the arima(3,1,0) model
```{r}
ar3=Arima(anc1p_ts, order=c(3,1,0))
ar3
tsdiag(ar3)
checkresiduals(ar3)#check the diagnostics, seems good
autoplot(forecast(ar3,h=3))
plot(anc1ptrue_ts)
backtest(ar3,anc1ptrue_ts,orig=52)

ar3_forecast <- data.frame(forecast(ar3,h=3)) %>%
  mutate(mnthyr=ymd(c("2022-04-01","2022-05-01","2022-06-01")),
         forecast=1) %>%
  select(mnthyr,
         rate=1,
         lower=4,
         upper=5,
         forecast)

ggplot(anc1p, aes(mnthyr, rate)) +
  geom_point(color="dodgerblue") +
  stat_smooth() +
  geom_point(data=ar3_forecast, aes(y=rate), color="darkgoldenrod2") +
  stat_smooth(data=ar3_forecast, aes(y=rate), color="darkgoldenrod2",fill="darkgoldenrod2") +
  geom_ribbon(data=ar3_forecast, aes(ymin=lower, ymax=upper),
              fill="darkgoldenrod2",
              alpha=.2) +
  scale_y_continuous(limits=c(0,.5),
                     labels=percent_format(accuracy=1))



```
#try arima(0,1,3)
```{r}
ma3=Arima(anc1p_ts, order=c(0,1,3))
ma3
tsdiag(ma3)
checkresiduals(ma3)#check the diagnostics, seems good
autoplot(forecast(ma3,h=3))
plot(anc1ptrue_ts)
backtest(ma3,anc1ptrue_ts,orig=52)

ma3_forecast <- data.frame(forecast(ma3,h=3)) %>%
  mutate(mnthyr=ymd(c("2022-04-01","2022-05-01","2022-06-01")),
         forecast=1) %>%
  select(mnthyr,
         rate=1,
         lower=4,
         upper=5,
         forecast)

ggplot(anc1p, aes(mnthyr, rate)) +
  geom_point(color="dodgerblue") +
  stat_smooth() +
  geom_point(data=ma3_forecast, aes(y=rate), color="darkgoldenrod2") +
  stat_smooth(data=ma3_forecast, aes(y=rate), color="darkgoldenrod2",fill="darkgoldenrod2") +
  geom_ribbon(data=ma3_forecast, aes(ymin=lower, ymax=upper),
              fill="darkgoldenrod2",
              alpha=.2) +
  scale_y_continuous(limits=c(0,.5),
                     labels=percent_format(accuracy=1))

```
#try arima(0,1,4)

```{r}
ma4=Arima(anc1p_ts, order=c(0,1,4))
ma4
tsdiag(ma4)
checkresiduals(ma4)#check the diagnostics, seems good
autoplot(forecast(ma4,h=3))
plot(anc1ptrue_ts)
backtest(ma4,anc1ptrue_ts,orig=52)

ma4_forecast <- data.frame(forecast(ma4,h=3)) %>%
  mutate(mnthyr=ymd(c("2022-04-01","2022-05-01","2022-06-01")),
         forecast=1) %>%
  select(mnthyr,
         rate=1,
         lower=4,
         upper=5,
         forecast)

ggplot(anc1p, aes(mnthyr, rate)) +
  geom_point(color="dodgerblue") +
  stat_smooth() +
  geom_point(data=ma4_forecast, aes(y=rate), color="darkgoldenrod2") +
  stat_smooth(data=ma4_forecast, aes(y=rate), color="darkgoldenrod2",fill="darkgoldenrod2") +
  geom_ribbon(data=ma4_forecast, aes(ymin=lower, ymax=upper),
              fill="darkgoldenrod2",
              alpha=.2) +
  scale_y_continuous(limits=c(0,.5),
                     labels=percent_format(accuracy=1))

```
#arima(0,1,4) with 0 coefficients for some ma parameters
```{r}
ma4_1=Arima(anc1p_ts, order=c(0,1,4), fixed=c(0,0,NA,NA))
ma4_1
tsdiag(ma4_1)
checkresiduals(ma4_1)#check the diagnostics, seems good
autoplot(forecast(ma4_1,h=3))
plot(anc1ptrue_ts)
backtest(ma4_1,anc1ptrue_ts,orig=52)

ma4_1_forecast <- data.frame(forecast(ma4_1,h=3)) %>%
  mutate(mnthyr=ymd(c("2022-04-01","2022-05-01","2022-06-01")),
         forecast=1) %>%
  select(mnthyr,
         rate=1,
         lower=4,
         upper=5,
         forecast)

ggplot(anc1p, aes(mnthyr, rate)) +
  geom_point(color="dodgerblue") +
  stat_smooth() +
  geom_point(data=ma4_1_forecast, aes(y=rate), color="darkgoldenrod2") +
  stat_smooth(data=ma4_1_forecast, aes(y=rate), color="darkgoldenrod2",fill="darkgoldenrod2") +
  geom_ribbon(data=ma4_1_forecast, aes(ymin=lower, ymax=upper),
              fill="darkgoldenrod2",
              alpha=.2) +
  scale_y_continuous(limits=c(0,.5),
                     labels=percent_format(accuracy=1))

```
#arima(4,1,4)
```{r}
arima414=Arima(anc1p_ts, order=c(4,1,4))
arima414
tsdiag(arima414)
checkresiduals(arima414)
#check the diagnostics, seems good
autoplot(forecast(arima414,h=3))
plot(anc1ptrue_ts)
backtest(arima414,anc1ptrue_ts,orig=52)

arima414_forecast <- data.frame(forecast(arima414,h=3)) %>%
  mutate(mnthyr=ymd(c("2022-04-01","2022-05-01","2022-06-01")),
         forecast=1) %>%
  select(mnthyr,
         rate=1,
         lower=4,
         upper=5,
         forecast)

ggplot(anc1p, aes(mnthyr, rate)) +
  geom_point(color="dodgerblue") +
  stat_smooth() +
  geom_point(data=arima414_forecast, aes(y=rate), color="darkgoldenrod2") +
  stat_smooth(data=arima414_forecast, aes(y=rate), color="darkgoldenrod2",fill="darkgoldenrod2") +
  geom_ribbon(data=arima414_forecast, aes(ymin=lower, ymax=upper),
              fill="darkgoldenrod2",
              alpha=.2) +
  scale_y_continuous(limits=c(0,.5),
                     labels=percent_format(accuracy=1))
```
#try d=2
```{r}
anc1p_arim2 <- auto.arima(d2)
anc1p_arim2# given arima220
```
#arima(2,2,0)
```{r}
arima220=Arima(anc1p_ts, order=c(2,2,0))
tsdiag(arima220)
autoplot(forecast(arima220,h=3))
plot(anc1ptrue_ts)
backtest(arima220,anc1ptrue_ts,orig=52)

arima220_forecast <- data.frame(forecast(arima220, h=3)) %>%
  mutate(mnthyr=ymd(c("2022-04-01","2022-05-01","2022-06-01")),
         forecast=1) %>%
  select(mnthyr,
         rate=1,
         lower=4,
         upper=5,
         forecast)
#here the forecast is the diff like Yt-Y(t-1)

ggplot(anc1p, aes(mnthyr, rate)) +
  geom_point(color="dodgerblue") +
  stat_smooth() +
  geom_point(data=arima220_forecast, aes(y=rate), color="darkgoldenrod2") +
  stat_smooth(data=arima220_forecast, aes(y=rate), color="darkgoldenrod2",fill="darkgoldenrod2") +
  geom_ribbon(data=arima220_forecast, aes(ymin=lower, ymax=upper),
              fill="darkgoldenrod2",
              alpha=.2) +
  scale_y_continuous(limits=c(0,.5),
                     labels=percent_format(accuracy=1))
#model not good
```